// <auto-generated />
using ChildDevelopmentLibrary.DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChildDevelopmentLibrary.DAL.Migrations
{
    [DbContext(typeof(DBWebsite))]
    [Migration("20221213224912_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChildDevelopmentLibrary.DAL.Entities.Child", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Igor",
                            LastName = "Radchuk",
                            ProgramId = 1L,
                            Status = 2
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Petro",
                            LastName = "Ostap",
                            ProgramId = 1L,
                            Status = 2
                        });
                });

            modelBuilder.Entity("ChildDevelopmentLibrary.DAL.Entities.EducationalProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "ASP.NET Core 7"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "PHP"
                        });
                });

            modelBuilder.Entity("ChildDevelopmentLibrary.DAL.Entities.Child", b =>
                {
                    b.HasOne("ChildDevelopmentLibrary.DAL.Entities.EducationalProgram", "Program")
                        .WithMany("Children")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("ChildDevelopmentLibrary.DAL.Entities.EducationalProgram", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
