// <auto-generated />
using System;
using ChildDevelopmentLibrary.DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChildDevelopmentLibrary.DAL.Migrations
{
    [DbContext(typeof(DBWebsite))]
    partial class DBWebsiteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChildDevelopmentLibrary.DAL.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Igor",
                            LastName = "Radchuk",
                            ProgramId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Petro",
                            LastName = "Ostapchuk",
                            ProgramId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ivan",
                            LastName = "Chug",
                            ProgramId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Andriy",
                            LastName = "Oshuta",
                            ProgramId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Nazar",
                            LastName = "Melnyk",
                            ProgramId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Dmitro",
                            LastName = "Honchar",
                            ProgramId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Stepan",
                            LastName = "Bandera",
                            ProgramId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Taras",
                            LastName = "Shevchenko",
                            ProgramId = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("ChildDevelopmentLibrary.DAL.Entities.EducationalProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ASP.NET Core 7"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("ChildDevelopmentLibrary.DAL.Entities.Child", b =>
                {
                    b.HasOne("ChildDevelopmentLibrary.DAL.Entities.EducationalProgram", "Program")
                        .WithMany("Children")
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("ChildDevelopmentLibrary.DAL.Entities.EducationalProgram", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
