version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: 
      dockerfile: Dockerfile
    image: webapi
    container_name: webapi
    ports:
      - "5000:80"
    depends_on: 
      - sqlserver2022
  sqlserver2022:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password